server:
  port: 8087

spring:
  data:
    mongodb:
      uri: 'mongodb://localhost:27017/person-db'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false
    mongo:
      enabled: false

info:
  app:
    name: @project.name@
